set(record "${CMAKE_CURRENT_BINARY_DIR}/roundtrip.frames")
execute_process(COMMAND "${APP}" --demo --steps 70 --record "${record}" --config "${CONFIG}"
    RESULT_VARIABLE result OUTPUT_VARIABLE demo ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Demo failed: ${error}")
endif()
if(NOT demo MATCHES ",following,")
    message(FATAL_ERROR "Demo never followed the tag")
endif()
if(NOT demo MATCHES ",0.000000,0.000000,insufficient_ranges,")
    message(FATAL_ERROR "Demo failed to stop for missing tag ranges")
endif()
execute_process(COMMAND "${APP}" --replay "${record}" --config "${CONFIG}"
    RESULT_VARIABLE result OUTPUT_VARIABLE replay ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT demo STREQUAL replay)
    message(FATAL_ERROR "Replay differs from recorded simulation: ${error}")
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/bad.frames" "FRAME 1 0 ODOM")
execute_process(COMMAND "${APP}" --replay "${CMAKE_CURRENT_BINARY_DIR}/bad.frames"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
    message(FATAL_ERROR "Truncated input accepted")
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/bad.conf" "max_speeed 10\n")
execute_process(COMMAND "${APP}" --demo --steps 1 --config "${CMAKE_CURRENT_BINARY_DIR}/bad.conf"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
    message(FATAL_ERROR "Misspelled config key accepted")
endif()
